/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SWHB
 */
public class AddItems extends javax.swing.JPanel {

    /**
     * Creates new form AddItems
     */
    int ItemID;
    String myID;
    String IP;
    public AddItems(String myID, String IP) {
        initComponents();
        this.myID=myID;
        
        this.IP=IP;
        lblError.setVisible(false);
        ItemID=getItemID();
        txtItemID4.setText(Integer.toString(ItemID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblID = new javax.swing.JLabel();
        txtItemID4 = new javax.swing.JTextField();
        cmsSeparator = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        cmsSeparator1 = new javax.swing.JSeparator();
        txtItemName = new javax.swing.JTextField();
        lbIQuantity = new javax.swing.JLabel();
        txtItemQuantity = new javax.swing.JTextField();
        cmsSeparator2 = new javax.swing.JSeparator();
        lbIPrice = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        cmsSeparator3 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 52, 60));
        setLayout(new java.awt.GridBagLayout());

        lblID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(153, 153, 153));
        lblID.setText("Item ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 80, 0, 0);
        add(lblID, gridBagConstraints);

        txtItemID4.setEditable(false);
        txtItemID4.setBackground(new java.awt.Color(52, 52, 60));
        txtItemID4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtItemID4.setForeground(new java.awt.Color(255, 255, 255));
        txtItemID4.setBorder(null);
        txtItemID4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemID4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemID4FocusLost(evt);
            }
        });
        txtItemID4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemID4KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 80, 0, 0);
        add(txtItemID4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 299;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 80, 0, 0);
        add(cmsSeparator, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(153, 153, 153));
        lblName.setText("Item Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 80, 0, 0);
        add(lblName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 299;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 80, 0, 0);
        add(cmsSeparator1, gridBagConstraints);

        txtItemName.setBackground(new java.awt.Color(52, 52, 60));
        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtItemName.setForeground(new java.awt.Color(255, 255, 255));
        txtItemName.setBorder(null);
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 80, 0, 0);
        add(txtItemName, gridBagConstraints);

        lbIQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIQuantity.setForeground(new java.awt.Color(153, 153, 153));
        lbIQuantity.setText("Item Quantity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 80, 0, 0);
        add(lbIQuantity, gridBagConstraints);

        txtItemQuantity.setBackground(new java.awt.Color(52, 52, 60));
        txtItemQuantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtItemQuantity.setForeground(new java.awt.Color(255, 255, 255));
        txtItemQuantity.setBorder(null);
        txtItemQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemQuantityFocusLost(evt);
            }
        });
        txtItemQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemQuantityKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 80, 0, 0);
        add(txtItemQuantity, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 299;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 80, 0, 0);
        add(cmsSeparator2, gridBagConstraints);

        lbIPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIPrice.setForeground(new java.awt.Color(153, 153, 153));
        lbIPrice.setText("Item Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 80, 0, 0);
        add(lbIPrice, gridBagConstraints);

        txtItemPrice.setBackground(new java.awt.Color(52, 52, 60));
        txtItemPrice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtItemPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtItemPrice.setText("1500");
        txtItemPrice.setBorder(null);
        txtItemPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemPriceFocusLost(evt);
            }
        });
        txtItemPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemPriceKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 310;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 80, 0, 112);
        add(txtItemPrice, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 309;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 80, 0, 112);
        add(cmsSeparator3, gridBagConstraints);

        btnSignUp.setBackground(new java.awt.Color(70, 80, 95));
        btnSignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Insert");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSignUpFocusGained(evt);
            }
        });
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 103, 0, 0);
        add(btnSignUp, gridBagConstraints);

        lblError.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Please Fill All the Fields");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 120, 34, 0);
        add(lblError, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 150, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemID4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemID4FocusGained
       
                
        lblError.setVisible(false);
        lblID.setForeground(Color.white);
    }//GEN-LAST:event_txtItemID4FocusGained

    private void txtItemID4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemID4FocusLost
        lblID.setForeground(new Color(153,153,153));
        
    

    }//GEN-LAST:event_txtItemID4FocusLost

    private void txtItemNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusGained
        lblError.setVisible(false);
        lblName.setForeground(Color.white);
    }//GEN-LAST:event_txtItemNameFocusGained

    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost
        lblName.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemNameFocusLost

    private void txtItemQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemQuantityFocusGained
        lblError.setVisible(false);
        lbIQuantity.setForeground(Color.white);
    }//GEN-LAST:event_txtItemQuantityFocusGained

    private void txtItemQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemQuantityFocusLost
        lbIQuantity.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemQuantityFocusLost

    private void txtItemPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemPriceFocusGained
        lblError.setVisible(false);
        lbIPrice.setForeground(Color.white);
    }//GEN-LAST:event_txtItemPriceFocusGained

    private void txtItemPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemPriceFocusLost
        // TODO add your handling code here:
        lbIPrice.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemPriceFocusLost

    private void btnSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSignUpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpFocusGained

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked

    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        btnSignUp.setBackground(new Color(225,150,100));
        btnSignUp.setForeground(Color.black);
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        btnSignUp.setBackground(new Color(70,80,95));
        btnSignUp.setForeground(Color.white);
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        Connection con;
        Statement st;
        ResultSet rs;
        if(!(txtItemName.getText().equals("") || txtItemPrice.getText().equals("") || txtItemQuantity.getText().equals("") || txtItemID4.getText().equals("")))
        {
            try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");

                String sql="Insert into Item values("+ItemID+",'"+txtItemName.getText()+"',"+Integer.parseInt(txtItemQuantity.getText())+","+Integer.parseInt(txtItemPrice.getText())+",'"+myID+"')";
                st=con.createStatement();
                rs=st.executeQuery(sql);

                JOptionPane.showMessageDialog(null, "Item Added Successfully");
                lblError.setVisible(false);

            }
            catch(Exception e)
            {
                     System.out.println(e.getMessage());
            }
        }
        else
        {
            lblError.setText("Please Fil All The Fields");
            lblError.setVisible(true);
        }

   

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtItemID4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemID4KeyTyped
         char c=evt.getKeyChar();
      if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE))
      {
          evt.consume();
      }
    }//GEN-LAST:event_txtItemID4KeyTyped

    private void txtItemQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemQuantityKeyTyped
         char c=evt.getKeyChar();
      if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE))
      {
          evt.consume();
      }
    }//GEN-LAST:event_txtItemQuantityKeyTyped

    private void txtItemPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemPriceKeyTyped
        char c=evt.getKeyChar();
      if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE))
      {
          evt.consume();
      }
    }//GEN-LAST:event_txtItemPriceKeyTyped

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JSeparator cmsSeparator;
    private javax.swing.JSeparator cmsSeparator1;
    private javax.swing.JSeparator cmsSeparator2;
    private javax.swing.JSeparator cmsSeparator3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIPrice;
    private javax.swing.JLabel lbIQuantity;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtItemID4;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtItemQuantity;
    // End of variables declaration//GEN-END:variables

    private int getItemID() {
        int id=0;
        Connection con;
        Statement st;
        ResultSet rs;
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");

                String sql="Select ItemID.nextval as \"ItemID\" from dual";
                st=con.createStatement();
                rs=st.executeQuery(sql);
                rs.next();
                id =rs.getInt("ItemID");
                
                }
             
            
            catch(Exception e)
            {
                  System.out.println(e.getMessage());
            }   
        return id;
    }
}
