/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JPanel;

/**
 *
 * @author SWHB
 */


public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    JPanel previous;
    GridBagConstraints c;
    String myID;
    String IP;
    public Admin(String myID,String IP) {
        initComponents();
                this.setSize(950,650);
                c= new GridBagConstraints();
                this.myID=myID;
                Connection con;
                
                this.IP=IP;
        Statement st;
        ResultSet rs;
        
            try
            {
                 Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");
            
            String sql="Select Username,Balance from AdminPanel where Username='"+myID+"'";
             
             st=con.createStatement();
            rs=st.executeQuery(sql);
             
           rs.next();
                lblName.setText(rs.getString("Username"));
                lblBalance.setText(Integer.toString(rs.getInt("Balance")));
             
         
            con.close();
            }
            catch(Exception e)
            {
               // System.out.println(e.getMessage());
            }

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblSetPayments = new javax.swing.JLabel();
        lblSellers = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblHistory = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(52, 52, 60));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Balance :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rs.");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setText("13000");

        lblSetPayments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSetPayments.setForeground(new java.awt.Color(153, 153, 153));
        lblSetPayments.setText("Send Payment");
        lblSetPayments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSetPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetPaymentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSetPaymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetPaymentsMouseExited(evt);
            }
        });

        lblSellers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSellers.setForeground(new java.awt.Color(153, 153, 153));
        lblSellers.setText("View All Sellers");
        lblSellers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSellersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSellersMouseExited(evt);
            }
        });

        lblCustomer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(153, 153, 153));
        lblCustomer.setText("View All Costomer");
        lblCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomerMouseExited(evt);
            }
        });

        lblHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHistory.setForeground(new java.awt.Color(153, 153, 153));
        lblHistory.setText("Transaction History");
        lblHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHistoryMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Syed Waqar Haider Bukhari");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHistory)
                            .addComponent(jLabel1)
                            .addComponent(lblCustomer)
                            .addComponent(lblSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSetPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBalance))
                .addGap(78, 78, 78)
                .addComponent(lblSetPayments)
                .addGap(29, 29, 29)
                .addComponent(lblSellers)
                .addGap(40, 40, 40)
                .addComponent(lblCustomer)
                .addGap(40, 40, 40)
                .addComponent(lblHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(73, 73, 73))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 630);

        mainPanel.setBackground(new java.awt.Color(52, 52, 60));
        mainPanel.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(mainPanel);
        mainPanel.setBounds(240, 0, 800, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSetPaymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetPaymentsMouseEntered
        lblSetPayments.setForeground(Color.white);
    }//GEN-LAST:event_lblSetPaymentsMouseEntered

    private void lblSetPaymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetPaymentsMouseExited
       lblSetPayments.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lblSetPaymentsMouseExited

    private void lblSellersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellersMouseEntered
        lblSellers.setForeground(Color.white);
    }//GEN-LAST:event_lblSellersMouseEntered

    private void lblSellersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellersMouseExited
    lblSellers.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lblSellersMouseExited

    private void lblCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseEntered
        lblCustomer.setForeground(Color.white);
    }//GEN-LAST:event_lblCustomerMouseEntered

    private void lblCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseExited
        lblCustomer.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lblCustomerMouseExited

    private void lblHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseEntered
       lblHistory.setForeground(Color.white);
    }//GEN-LAST:event_lblHistoryMouseEntered

    private void lblHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseExited
        lblHistory.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lblHistoryMouseExited

    private void lblSetPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetPaymentsMouseClicked
                        try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new SendMoney(myID, lblBalance);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
                c.gridx=0;
       c.gridy=0;
       previous=new SendMoney(myID, lblBalance);
       
       mainPanel.add(previous,c);
       }
           

    }//GEN-LAST:event_lblSetPaymentsMouseClicked

    private void lblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseClicked
                          try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new HistoryforAdmin(myID);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
                c.gridx=0;
       c.gridy=0;
       previous=new HistoryforAdmin(myID);
       
       mainPanel.add(previous,c);
       }
    }//GEN-LAST:event_lblHistoryMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
     
        this.setVisible(false);
        new LogIn(IP).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSellers;
    private javax.swing.JLabel lblSetPayments;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
