/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SWHB
 */
public class AmountHIstory extends javax.swing.JPanel {

    /**
     * Creates new form ShowShops
     */
    public AmountHIstory(String myID) {
        initComponents();
        
        populateTable(myID);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane2 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        tabe2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        withdrawHistoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 52, 60));
        setLayout(new java.awt.GridBagLayout());

        tab1.setBackground(new java.awt.Color(52, 52, 60));
        tab1.setLayout(null);
        tab1.add(jTabbedPane1);
        jTabbedPane1.setBounds(50, -20, 5, 5);

        historyTable.setBackground(new java.awt.Color(214, 217, 223));
        historyTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender Name", "Reciever Name", "Amount (Rs.)", "Date "
            }
        ));
        jScrollPane2.setViewportView(historyTable);

        tab1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 610, 470);

        jTabbedPane2.addTab("Transaction History", tab1);

        tabe2.setBackground(new java.awt.Color(52, 52, 60));
        tabe2.setLayout(null);

        withdrawHistoryTable.setBackground(new java.awt.Color(214, 217, 223));
        withdrawHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Date"
            }
        ));
        jScrollPane1.setViewportView(withdrawHistoryTable);

        tabe2.add(jScrollPane1);
        jScrollPane1.setBounds(12, 12, 600, 430);

        jTabbedPane2.addTab("Withdraw History", tabe2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 521;
        gridBagConstraints.ipady = 446;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 80, 33, 67);
        add(jTabbedPane2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transactions History");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 200, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tabe2;
    private javax.swing.JTable withdrawHistoryTable;
    // End of variables declaration//GEN-END:variables
    
    private void populateTable(String myID) {
         Connection con;
        Statement st;
        ResultSet rs;
        
            try
            {
                 Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");
            
            String sql="Select \"Sender Name\",\"Reciever Name\",Amount,Transfer_date from customertransaction where Sender_ID='"+myID+"'";
              st=con.createStatement();
            rs=st.executeQuery(sql);
            
            historyTable.setModel(DbUtils.resultSetToTableModel(rs));
            String sql1="Select Amount,Withdraw_date from Withdrawl where Sender_ID='"+myID+"'";
              st=con.createStatement();
              rs=st.executeQuery(sql1);
              
             withdrawHistoryTable.setModel(DbUtils.resultSetToTableModel(rs));
            
           con.close();
            }
            catch(Exception e)
            {
               System.out.println(e.getMessage());
            }
    }
}
