/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JPanel;

/**
 *
 * @author SWHB
 */
public class SellerDashboard extends javax.swing.JFrame {

    GridBagConstraints c;
    
  
    
   
   String IP;
    JPanel previous;
    public SellerDashboard(String myID,String IP) {
        initComponents();
       
        c= new GridBagConstraints();
      
        this.setSize(1200,700);
        this.setLocationRelativeTo(this);
        this.IP=IP;
        this.myID=myID;
        Connection con;
        Statement st;
        ResultSet rs;
        
            try
            {
                 Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");
            
            String sql="Select Shop_Name, Balance from Seller where Shop_ID='"+myID+"'";
             
             st=con.createStatement();
            rs=st.executeQuery(sql);
             
           rs.next();
                lblName.setText(rs.getString("Shop_Name"));
                lblBalance.setText(Integer.toString(rs.getInt("Balance")));
             
         
            con.close();
            }
            catch(Exception e)
            {
               System.out.println(e.getMessage());
            }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblOpen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblOpen1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        transfer = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblOpen5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hiistory = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblOpen6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        viewCart = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblOpen7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblOpen8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        lblOpen9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Logout1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lblOpen10 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(52, 52, 60));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-list-32.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(600, 820, 60, 50);
        mainPanel.add(jLabel2, gridBagConstraints);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(310, 0, 910, 700);

        jPanel2.setBackground(new java.awt.Color(34, 33, 38));
        jPanel2.setLayout(null);

        jPanel4.setLayout(null);
        jPanel2.add(jPanel4);
        jPanel4.setBounds(108, 20, 0, 0);

        jPanel5.setLayout(null);

        jLabel1.setText("       Student Pic");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 100, 100);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(80, 20, 0, 0);

        lb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 255, 255));
        lb.setText("Shop Balance (Rs.) : ");
        jPanel2.add(lb);
        lb.setBounds(30, 150, 170, 22);

        jPanel3.setLayout(null);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 34, 14);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(90, 20, 0, 0);

        lblOpen.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpenMouseExited(evt);
            }
        });
        lblOpen.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View Sale History");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen.add(jLabel4);
        jLabel4.setBounds(90, 10, 210, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen.add(jLabel5);
        jLabel5.setBounds(30, 0, 32, 50);

        lblOpen1.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen1MouseExited(evt);
            }
        });
        lblOpen1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Show Open Show");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen1.add(jLabel6);
        jLabel6.setBounds(100, 12, 150, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen1.add(jLabel7);
        jLabel7.setBounds(30, 0, 32, 50);

        lblOpen.add(lblOpen1);
        lblOpen1.setBounds(0, 180, 310, 50);

        jPanel2.add(lblOpen);
        lblOpen.setBounds(0, 190, 310, 50);

        transfer.setBackground(new java.awt.Color(33, 34, 38));
        transfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferMouseExited(evt);
            }
        });
        transfer.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Withdraw Amount");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transfer.add(jLabel12);
        jLabel12.setBounds(100, 12, 150, 20);

        lblOpen5.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen5MouseExited(evt);
            }
        });
        lblOpen5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Show Open Show");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen5.add(jLabel14);
        jLabel14.setBounds(100, 12, 150, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen5.add(jLabel15);
        jLabel15.setBounds(30, 0, 32, 50);

        transfer.add(lblOpen5);
        lblOpen5.setBounds(0, 180, 310, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money-32.png"))); // NOI18N
        transfer.add(jLabel16);
        jLabel16.setBounds(30, 10, 32, 32);

        jPanel2.add(transfer);
        transfer.setBounds(0, 260, 310, 50);

        hiistory.setBackground(new java.awt.Color(33, 34, 38));
        hiistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hiistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hiistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hiistoryMouseExited(evt);
            }
        });
        hiistory.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Transaction History");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hiistory.add(jLabel13);
        jLabel13.setBounds(100, 12, 170, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-32.png"))); // NOI18N
        hiistory.add(jLabel17);
        jLabel17.setBounds(22, 0, 40, 50);

        lblOpen6.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen6MouseExited(evt);
            }
        });
        lblOpen6.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Show Open Show");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen6.add(jLabel18);
        jLabel18.setBounds(100, 12, 150, 20);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen6.add(jLabel19);
        jLabel19.setBounds(30, 0, 32, 50);

        hiistory.add(lblOpen6);
        lblOpen6.setBounds(0, 180, 310, 50);

        jPanel2.add(hiistory);
        hiistory.setBounds(0, 330, 310, 50);

        viewCart.setBackground(new java.awt.Color(33, 34, 38));
        viewCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewCartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewCartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewCartMouseExited(evt);
            }
        });
        viewCart.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("View Stock");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewCart.add(jLabel20);
        jLabel20.setBounds(100, 12, 160, 20);

        lblOpen7.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen7MouseExited(evt);
            }
        });
        lblOpen7.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Show Open Show");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen7.add(jLabel21);
        jLabel21.setBounds(100, 12, 150, 20);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen7.add(jLabel22);
        jLabel22.setBounds(30, 0, 32, 50);

        viewCart.add(lblOpen7);
        lblOpen7.setBounds(0, 180, 310, 50);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-11-32.png"))); // NOI18N
        viewCart.add(jLabel23);
        jLabel23.setBounds(40, 10, 32, 32);

        jPanel2.add(viewCart);
        viewCart.setBounds(0, 470, 310, 50);

        settings.setBackground(new java.awt.Color(33, 34, 38));
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });
        settings.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Settings");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.add(jLabel24);
        jLabel24.setBounds(100, 12, 150, 20);

        lblOpen8.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen8MouseExited(evt);
            }
        });
        lblOpen8.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Show Open Show");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen8.add(jLabel25);
        jLabel25.setBounds(100, 12, 150, 20);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen8.add(jLabel26);
        jLabel26.setBounds(30, 0, 32, 50);

        settings.add(lblOpen8);
        lblOpen8.setBounds(0, 180, 310, 50);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings-9-32.png"))); // NOI18N
        settings.add(jLabel27);
        jLabel27.setBounds(32, 10, 30, 32);

        jPanel2.add(settings);
        settings.setBounds(0, 400, 310, 50);

        Logout.setBackground(new java.awt.Color(33, 34, 38));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Log Out");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.add(jLabel30);
        jLabel30.setBounds(100, 12, 150, 20);

        lblOpen9.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen9MouseExited(evt);
            }
        });
        lblOpen9.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Show Open Show");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen9.add(jLabel31);
        jLabel31.setBounds(100, 12, 150, 20);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen9.add(jLabel32);
        jLabel32.setBounds(30, 0, 32, 50);

        Logout.add(lblOpen9);
        lblOpen9.setBounds(0, 180, 310, 50);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-32.png"))); // NOI18N
        Logout.add(jLabel33);
        jLabel33.setBounds(40, 10, 32, 32);

        Logout1.setBackground(new java.awt.Color(33, 34, 38));
        Logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout1MouseExited(evt);
            }
        });
        Logout1.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Log Out");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout1.add(jLabel34);
        jLabel34.setBounds(100, 12, 150, 20);

        lblOpen10.setBackground(new java.awt.Color(33, 34, 38));
        lblOpen10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpen10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpen10MouseExited(evt);
            }
        });
        lblOpen10.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Show Open Show");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpen10.add(jLabel35);
        jLabel35.setBounds(100, 12, 150, 20);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openShops.png"))); // NOI18N
        lblOpen10.add(jLabel36);
        jLabel36.setBounds(30, 0, 32, 50);

        Logout1.add(lblOpen10);
        lblOpen10.setBounds(0, 180, 310, 50);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-32.png"))); // NOI18N
        Logout1.add(jLabel37);
        jLabel37.setBounds(40, 10, 32, 32);

        Logout.add(Logout1);
        Logout1.setBounds(0, 560, 310, 50);

        jPanel2.add(Logout);
        Logout.setBounds(0, 540, 310, 50);

        lblBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setText("0.00");
        jPanel2.add(lblBalance);
        lblBalance.setBounds(200, 150, 100, 22);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Icon by Gouri's");
        jPanel2.add(lblName);
        lblName.setBounds(30, 120, 270, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 310, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOpenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMouseEntered
       lblOpen.setBackground(new Color(52,52,60)); 
    }//GEN-LAST:event_lblOpenMouseEntered

    private void lblOpenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMouseExited
        lblOpen.setBackground(new Color(34,33,38)); 
    }//GEN-LAST:event_lblOpenMouseExited

    private void lblOpen1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen1MouseEntered

    private void lblOpen1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen1MouseExited

    private void lblOpen5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen5MouseEntered

    private void lblOpen5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen5MouseExited

    private void transferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseEntered
       transfer.setBackground(new Color(52,52,60));
    }//GEN-LAST:event_transferMouseEntered

    private void transferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseExited
        transfer.setBackground(new Color(34,33,38));
    }//GEN-LAST:event_transferMouseExited

    private void lblOpen6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen6MouseEntered

    private void lblOpen6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen6MouseExited

    private void hiistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiistoryMouseEntered
        hiistory.setBackground(new Color(52,52,60));
    }//GEN-LAST:event_hiistoryMouseEntered

    private void hiistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiistoryMouseExited
             hiistory.setBackground(new Color(34,33,38));
    }//GEN-LAST:event_hiistoryMouseExited

    private void lblOpen7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen7MouseEntered

    private void lblOpen7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen7MouseExited

    private void viewCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCartMouseEntered
        viewCart.setBackground(new Color(52,52,60));
    }//GEN-LAST:event_viewCartMouseEntered

    private void viewCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCartMouseExited
       viewCart.setBackground(new Color(34,33,38));
    }//GEN-LAST:event_viewCartMouseExited

    private void lblOpen8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen8MouseEntered

    private void lblOpen8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen8MouseExited

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
        settings.setBackground(new Color(52,52,60));
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
     settings.setBackground(new Color(34,33,38));
    }//GEN-LAST:event_settingsMouseExited

    private void lblOpen9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen9MouseEntered

    private void lblOpen9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen9MouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Logout.setBackground(new Color(52,52,60));  
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        Logout.setBackground(new Color(34,33,38));
    }//GEN-LAST:event_LogoutMouseExited

    private void lblOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMouseClicked
       
        
        try
       {
       previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new SaleHistory(myID, IP);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
       c.gridx=0;
       c.gridy=0;
       previous=new SaleHistory(myID, IP);
       
       mainPanel.add(previous,c);
           
       }
        
        
     
    }//GEN-LAST:event_lblOpenMouseClicked

    private void viewCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCartMouseClicked
        
        
        try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new Stock(myID, mainPanel, c,previous, IP);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
       c.gridx=0;
       c.gridy=0;
       previous=new Stock(myID, mainPanel,c,previous, IP);
       
       mainPanel.add(previous,c);
           
       }
        
        
       
    }//GEN-LAST:event_viewCartMouseClicked

    private void hiistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiistoryMouseClicked
                try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new HistoryforSeller(myID,IP);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
                c.gridx=0;
       c.gridy=0;
       previous=new HistoryforSeller(myID,IP);
       
       mainPanel.add(previous,c);
           
       }
    }//GEN-LAST:event_hiistoryMouseClicked

    private void transferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseClicked
                try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new SellerTransferMoney(myID, lblBalance,IP);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
                c.gridx=0;
       c.gridy=0;
       previous=new SellerTransferMoney(myID, lblBalance,IP);
       
       mainPanel.add(previous,c);
       }
    }//GEN-LAST:event_transferMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        
           try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new SellerSettings(myID,IP);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
                c.gridx=0;
       c.gridy=0;
       previous=new SellerSettings(myID,IP);
       
       mainPanel.add(previous,c);
           
       }
    }//GEN-LAST:event_settingsMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
          Connection con;
        Statement st;
        ResultSet rs;
        
            try
            {
                 Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");
            
            String sq="update Seller set Available=0 where Shop_ID='"+myID+"'";
             
             st=con.createStatement();
            rs=st.executeQuery(sq);
                
             
         
            con.close();
            }
            catch(Exception e)
            {
               System.out.println(e.getMessage());
            }
       
        
        
        this.setVisible(false);
       new LogIn(IP).setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void lblOpen10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen10MouseEntered

    private void lblOpen10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpen10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpen10MouseExited

    private void Logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout1MouseClicked

    private void Logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout1MouseEntered

    private void Logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout1MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
                     try
       {
          previous.setVisible(false);
       c.gridx=0;
       c.gridy=0;
       previous=new AddItems(myID, IP);
       
       mainPanel.add(previous,c);
       }
       catch(Exception e)
       {
                c.gridx=0;
       c.gridy=0;
       previous=new AddItems(myID, IP);
       
       mainPanel.add(previous,c);
       }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerDashboard(myID,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Logout1;
    private javax.swing.JPanel hiistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel lblOpen;
    private javax.swing.JPanel lblOpen1;
    private javax.swing.JPanel lblOpen10;
    private javax.swing.JPanel lblOpen5;
    private javax.swing.JPanel lblOpen6;
    private javax.swing.JPanel lblOpen7;
    private javax.swing.JPanel lblOpen8;
    private javax.swing.JPanel lblOpen9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel settings;
    private javax.swing.JPanel transfer;
    private javax.swing.JPanel viewCart;
    // End of variables declaration//GEN-END:variables
    static private String myID;
}
