/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SWHB
 */
public class Stock extends javax.swing.JPanel {

    /**
     * Creates new form ShowShops
     */
    
    String myID;
    JPanel mainPanel, previous;
    GridBagConstraints c;
    String IP;
    public Stock(String myID, JPanel mainPanel, GridBagConstraints c, JPanel previous, String IP) {
        initComponents();
        this.myID=myID;
        this.IP=IP;
        this.mainPanel=mainPanel;
       loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList();
        lblSearch = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setBackground(new java.awt.Color(52, 52, 60));
        setLayout(new java.awt.GridBagLayout());

        txtSearch.setBackground(new java.awt.Color(52, 52, 60));
        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 279;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 150, 0, 0);
        add(txtSearch, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 278;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 150, 0, 0);
        add(jSeparator1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 170, 0, 0);
        add(jLabel1, gridBagConstraints);

        historyList.setBackground(new java.awt.Color(52, 52, 60));
        historyList.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        historyList.setForeground(new java.awt.Color(255, 255, 255));
        historyList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyListMouseClicked(evt);
            }
        });
        historyList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                historyListKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(historyList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 507;
        gridBagConstraints.ipady = 307;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 51, 59);
        add(jScrollPane2, gridBagConstraints);

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(153, 153, 153));
        lblSearch.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 150, 0, 0);
        add(lblSearch, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        lblSearch.setForeground(Color.white);
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        lblSearch.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtSearchFocusLost

    private void historyListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_historyListKeyReleased
         
         
//               for(int o=0; o<makeIndex; o++)
//             {
//                 System.out.println(searchedItemName[o]);
//             }
//            
    }//GEN-LAST:event_historyListKeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
             ItemFiltered=0;  
        filteredItemIndex=0;
        makeIndex=0;
       
       
        Items.removeAllElements();
        for(int p=0; p<noOfItems; p++)
               {
                   if(searchItem[p].toLowerCase().contains(txtSearch.getText().toLowerCase()))
                   {
                       
                       ItemFiltered++;
                   }
               }
               filteredIndexes= new int[ItemFiltered];
               for(int p=0; p<noOfItems; p++)
               {
                   if(searchItem[p].toLowerCase().contains(txtSearch.getText().toLowerCase()))
                   {
                       filteredIndexes[filteredItemIndex]=p;
                       
                        searchAddItem(p);
                       filteredItemIndex++;
                   }
               }
               //searchAddItem(filteredItemIndex,filteredIndexes,ItemName,ItemPrice,ItemQuantity);
                historyList.setModel(Items);
        historyList.setCellRenderer(new StockItemPanel());
    
    }//GEN-LAST:event_txtSearchKeyReleased

    private void historyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyListMouseClicked
        int index=historyList.getSelectedIndex();
        System.out.println(searchedItemName[historyList.getSelectedIndex()]);
         Updates up= new Updates(searchedItemID[index],searchedItemName[index],searchedItemPrice[index],searchedItemQuantity[index],myID, IP);
          up.setPanel(mainPanel, previous,c);
         up.setVisible(true);
        
        
    }//GEN-LAST:event_historyListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList historyList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
   DefaultListModel<StockItemObject> Items= new DefaultListModel<StockItemObject>();
 
      String[] searchItem;
      String[] ItemName;
      int[] ItemQuantity;
      int[] ItemPrice;
      int[] ItemID;
      
      int filteredIndexes[];
      int ItemIndex=0;
      int noOfItems=0;
      int ItemFiltered=0;
       int filteredItemIndex=0;
      
       int makeIndex=0;
   
       
        String[] searchedItemName;
      int[] searchedItemQuantity;
      int[] searchedItemPrice;
      int[] searchedItemID;
    
    public void loadData()
    {
         Connection con;
        Statement st;
        ResultSet rs;
         try
            {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");
            
            String sq2="Select Count(Item_ID) as \"Number\" from Item where Shop_ID='"+myID+"'";
               
             st=con.createStatement();
            rs=st.executeQuery(sq2);
            rs.next();
            noOfItems=rs.getInt("Number");
                System.out.println("No Of Items : "+noOfItems);           
            String sql="Select * from Item Where Shop_ID='"+myID+"'";
             st=con.createStatement();
            rs=st.executeQuery(sql);
             AddItems(rs); 
            
            con.close();
            }
            catch(Exception e)
            {
                System.out.println("in Load Data");
                System.out.println(e.getMessage());
            }
    }
    public void AddItems(ResultSet rs)
   {
        ItemIndex=0;
       searchItem=new String[noOfItems];
       
       ItemName= new String[noOfItems];
        ItemPrice= new int[noOfItems];
        ItemQuantity= new int[noOfItems];
       ItemID=new int[noOfItems];
        
       searchedItemName= new String[noOfItems];
        searchedItemPrice= new int[noOfItems];
        searchedItemQuantity= new int[noOfItems];
       searchedItemID= new int[noOfItems];
       
       try
       {
       while(rs.next())
       {
           Items.addElement(new StockItemObject(rs.getString("Item_Name"),rs.getInt("Quantity"),rs.getInt("Item_ID"),rs.getInt("Price")));
           searchItem[ItemIndex]=rs.getString("Item_Name")+" "+Integer.toString(rs.getInt("Quantity"))+" "+Integer.toString(rs.getInt("Price"))+" "+Integer.toString(rs.getInt("Item_ID"));
        ItemName[ItemIndex]=rs.getString("Item_Name");
        ItemQuantity[ItemIndex]=rs.getInt("Quantity");
        ItemPrice[ItemIndex]=rs.getInt("Price");
        ItemID[ItemIndex]=rs.getInt("Item_ID");
        
        ItemIndex++;
       }
       historyList.setModel(Items);
       historyList.setCellRenderer(new StockItemPanel());
       }
       catch(Exception e)
       {
           System.out.println("In Add Item Method");
           System.out.println(e.getMessage());
       }
       for(int j=0; j<noOfItems; j++)
        {
        searchedItemName[j]=ItemName[j];
        searchedItemQuantity[j]=ItemQuantity[j];
        searchedItemPrice[j]=ItemPrice[j];
        searchedItemID[j]=ItemID[j];
        }
   }
       public void searchAddItem(int index)//int noOfFilteredItem, int[] filteredIndexes, String[] ItemName, String[] ItemPrice, String[] ItemQuantity)
    {
       //System.out.println(ItemName[index]+ItemPrice[index]);
        searchedItemName[makeIndex]=ItemName[index];
        searchedItemQuantity[makeIndex]=ItemQuantity[index];
        searchedItemPrice[makeIndex]=ItemPrice[index];
        searchedItemID[makeIndex]=ItemID[index];
         
        Items.addElement(new StockItemObject(ItemName[index],ItemQuantity[index],ItemID[index],ItemPrice[index]));
        makeIndex++;
    } 
    

}
