/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author SWHB
 */
public class Updates extends javax.swing.JFrame {

    /**
     * Creates new form Updates
     */
    int ItemID, Quantity,price;
    String ItemName,myID;
  
    private JPanel Panel, previous;
    GridBagConstraints c;
    String IP;
    public Updates(int ItemID, String ItemName, int Price, int Quantity, String myID, String IP) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.ItemID=ItemID;
        this.ItemName=ItemName;
        this.Quantity=Quantity;
        this.IP=IP;
        this.price=Price;
        txtItemID4.setText(Integer.toString(ItemID));
         txtItemName.setText(ItemName);
          txtItemPrice.setText(Integer.toString(price));
           txtItemQuantity.setText(Integer.toString(Quantity));
            this.myID=myID;
              lblError.setVisible(false);
           c= new GridBagConstraints();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel4 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtItemID4 = new javax.swing.JTextField();
        cmsSeparator = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        cmsSeparator1 = new javax.swing.JSeparator();
        lbIQuantity = new javax.swing.JLabel();
        txtItemQuantity = new javax.swing.JTextField();
        cmsSeparator2 = new javax.swing.JSeparator();
        lbIPrice = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        cmsSeparator3 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        mainPanel4.setBackground(new java.awt.Color(52, 52, 60));
        mainPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        mainPanel4.setLayout(null);

        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(153, 153, 153));
        lblID.setText("Item ID");
        mainPanel4.add(lblID);
        lblID.setBounds(90, 20, 55, 17);

        txtItemID4.setEditable(false);
        txtItemID4.setBackground(new java.awt.Color(52, 52, 60));
        txtItemID4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemID4.setForeground(new java.awt.Color(255, 255, 255));
        txtItemID4.setText("1");
        txtItemID4.setBorder(null);
        txtItemID4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemID4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemID4FocusLost(evt);
            }
        });
        mainPanel4.add(txtItemID4);
        txtItemID4.setBounds(90, 50, 185, 36);
        mainPanel4.add(cmsSeparator);
        cmsSeparator.setBounds(90, 90, 185, 10);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(153, 153, 153));
        lblName.setText("Item Name");
        mainPanel4.add(lblName);
        lblName.setBounds(90, 110, 78, 17);

        txtItemName.setBackground(new java.awt.Color(52, 52, 60));
        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemName.setForeground(new java.awt.Color(255, 255, 255));
        txtItemName.setText("Fries");
        txtItemName.setBorder(null);
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        mainPanel4.add(txtItemName);
        txtItemName.setBounds(90, 140, 185, 36);
        mainPanel4.add(cmsSeparator1);
        cmsSeparator1.setBounds(90, 180, 185, 10);

        lbIQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIQuantity.setForeground(new java.awt.Color(153, 153, 153));
        lbIQuantity.setText("Item Quantity");
        mainPanel4.add(lbIQuantity);
        lbIQuantity.setBounds(90, 210, 98, 17);

        txtItemQuantity.setBackground(new java.awt.Color(52, 52, 60));
        txtItemQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemQuantity.setForeground(new java.awt.Color(255, 255, 255));
        txtItemQuantity.setText("1500");
        txtItemQuantity.setBorder(null);
        txtItemQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemQuantityFocusLost(evt);
            }
        });
        mainPanel4.add(txtItemQuantity);
        txtItemQuantity.setBounds(90, 240, 185, 36);
        mainPanel4.add(cmsSeparator2);
        cmsSeparator2.setBounds(90, 280, 185, 10);

        lbIPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIPrice.setForeground(new java.awt.Color(153, 153, 153));
        lbIPrice.setText("Item Price");
        mainPanel4.add(lbIPrice);
        lbIPrice.setBounds(90, 300, 71, 17);

        txtItemPrice.setBackground(new java.awt.Color(52, 52, 60));
        txtItemPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtItemPrice.setText("1500");
        txtItemPrice.setBorder(null);
        txtItemPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemPriceFocusLost(evt);
            }
        });
        mainPanel4.add(txtItemPrice);
        txtItemPrice.setBounds(90, 330, 185, 36);
        mainPanel4.add(cmsSeparator3);
        cmsSeparator3.setBounds(90, 370, 185, 10);

        btnSignUp.setBackground(new java.awt.Color(70, 80, 95));
        btnSignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Update");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSignUpFocusGained(evt);
            }
        });
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        mainPanel4.add(btnSignUp);
        btnSignUp.setBounds(200, 390, 77, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close-window-24.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        mainPanel4.add(jLabel1);
        jLabel1.setBounds(350, 10, 24, 30);

        lblError.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Please Fill All the Fields");
        mainPanel4.add(lblError);
        lblError.setBounds(50, 430, 310, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemID4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemID4FocusGained
        lblError.setVisible(false);
        lblID.setForeground(Color.white);
    }//GEN-LAST:event_txtItemID4FocusGained

    private void txtItemID4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemID4FocusLost
        lblID.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemID4FocusLost

    private void txtItemNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusGained
         lblError.setVisible(false);
        lblName.setForeground(Color.white);
    }//GEN-LAST:event_txtItemNameFocusGained

    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost
        lblName.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemNameFocusLost

    private void txtItemQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemQuantityFocusGained
          lblError.setVisible(false);
        lbIQuantity.setForeground(Color.white);
    }//GEN-LAST:event_txtItemQuantityFocusGained

    private void txtItemQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemQuantityFocusLost
        lbIQuantity.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemQuantityFocusLost

    private void txtItemPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemPriceFocusGained
          lblError.setVisible(false);
        lbIPrice.setForeground(Color.white);
    }//GEN-LAST:event_txtItemPriceFocusGained

    private void txtItemPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemPriceFocusLost
        // TODO add your handling code here:
        lbIPrice.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtItemPriceFocusLost

    private void btnSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSignUpFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSignUpFocusGained

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked

    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        btnSignUp.setBackground(new Color(225,150,100));
        btnSignUp.setForeground(Color.black);
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        btnSignUp.setBackground(new Color(70,80,95));
        btnSignUp.setForeground(Color.white);
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        Connection con;
        Statement st;
        ResultSet rs;
        if(!(txtItemName.getText().equals("") || txtItemPrice.getText().equals("") || txtItemQuantity.getText().equals("") || txtItemID4.getText().equals("")))
        {
            try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","bukhari");

                String sql="Update Item set Item_Name='"+txtItemName.getText()+"',Price="+Integer.parseInt(txtItemPrice.getText())+",Quantity="+Integer.parseInt(txtItemQuantity.getText())+" where Shop_ID='"+myID+"' and Item_ID="+Integer.parseInt(txtItemID4.getText())+"";
                st=con.createStatement();
                rs=st.executeQuery(sql);

              
             lblError.setText("All Changes Has Been Saved");
             lblError.setVisible(true);
         

        }
           catch(Exception e)
           {
               
           }
        }
               else
        {
            lblError.setText("Please Fil All The Fields");
             lblError.setVisible(true);
        }
        
        /////////////////////////
//        try
//       {
//          previous.setVisible(false);
//       c.gridx=0;
//       c.gridy=0;
//       previous=new Stock(myID,Panel,c,previous);
//       
//       Panel.add(previous,c);
//       }
//       catch(Exception e)
//       {
//       c.gridx=0;
//       c.gridy=0;
//       previous=new Stock(myID,Panel,c,previous);
//       
//       Panel.add(previous,c);
//           
//       }
//       
     ///////////////
        
        
        
     
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updates(0,"",0,0,"", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JSeparator cmsSeparator;
    private javax.swing.JSeparator cmsSeparator1;
    private javax.swing.JSeparator cmsSeparator2;
    private javax.swing.JSeparator cmsSeparator3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIPrice;
    private javax.swing.JLabel lbIQuantity;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel mainPanel4;
    private javax.swing.JTextField txtItemID4;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtItemQuantity;
    // End of variables declaration//GEN-END:variables

public void setPanel(JPanel mainPanel, JPanel previous, GridBagConstraints c)
{
    this.Panel=mainPanel;
    this.previous=previous;
   // this.c=c;
            
}

}
