/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author SWHB
 */
public class AdminHistoryItemPanel extends javax.swing.JPanel implements ListCellRenderer<AdminHistoryItemObject>{

    /**
     * Creates new form ItemPanel
     */
    public AdminHistoryItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTo = new javax.swing.JLabel();
        lnl = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lnl1 = new javax.swing.JLabel();
        lnl2 = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lnl3 = new javax.swing.JLabel();

        panel.setBackground(new java.awt.Color(34, 33, 38));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 52, 60), 2, true));
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMouseExited(evt);
            }
        });
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTo.setForeground(new java.awt.Color(255, 255, 255));
        lblTo.setText("Admin");
        panel.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 27));

        lnl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnl.setForeground(new java.awt.Color(255, 255, 255));
        lnl.setText("To:");
        panel.add(lnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("28-Nov-2018");
        panel.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount.setText("200");
        panel.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 70, 30));

        lnl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnl1.setForeground(new java.awt.Color(255, 255, 255));
        lnl1.setText("Rs.");
        panel.add(lnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 20, 30));

        lnl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnl2.setForeground(new java.awt.Color(255, 255, 255));
        lnl2.setText("From:");
        panel.add(lnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));

        lblFrom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrom.setForeground(new java.awt.Color(255, 255, 255));
        lblFrom.setText("You");
        panel.add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 27));

        lnl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnl3.setForeground(new java.awt.Color(255, 255, 255));
        lnl3.setText("Amount:");
        panel.add(lnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseExited
        panel.setBackground(new Color(34,33,38));
    }//GEN-LAST:event_panelMouseExited

    private void panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseEntered
        System.out.println("Mouse Entered");
        panel.setBackground(new Color(135,206,250));
    }//GEN-LAST:event_panelMouseEntered

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        
    }//GEN-LAST:event_panelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lnl;
    private javax.swing.JLabel lnl1;
    private javax.swing.JLabel lnl2;
    private javax.swing.JLabel lnl3;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

   



    @Override
    public Component getListCellRendererComponent(JList<? extends AdminHistoryItemObject> jlist, AdminHistoryItemObject e, int i, boolean bln, boolean bln1) {
         lblTo.setText(e.to);
       lblFrom.setText(e.from);
       lblAmount.setText(Integer.toString(e.amount));
       lblDate.setText(e.date);
        return this;
    }

  
}
