/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vpaysystem;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author SWHB
 */
public class Welcom extends javax.swing.JFrame {

    public String IP="10.102.163.236";

    public Welcom() {
        initComponents();
        this.setSize(1200,700);
        welcomePanel.setBackground(new Color(70,70,70));
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSeller = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(2048, 1365));
        getContentPane().setLayout(null);

        welcomePanel.setBackground(new java.awt.Color(70, 70, 70));
        welcomePanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");
        welcomePanel.add(jLabel2);
        jLabel2.setBounds(530, 90, 70, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Virtual Payment System");
        welcomePanel.add(jLabel3);
        jLabel3.setBounds(270, 360, 630, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome");
        welcomePanel.add(jLabel4);
        jLabel4.setBounds(440, 20, 250, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SibaLogo.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 51), new java.awt.Color(51, 0, 204)));
        welcomePanel.add(jLabel5);
        jLabel5.setBounds(450, 170, 220, 180);

        lblCustomer.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer.setText("Customer");
        lblCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomerMouseExited(evt);
            }
        });
        welcomePanel.add(lblCustomer);
        lblCustomer.setBounds(460, 540, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New User? SignUp as");
        welcomePanel.add(jLabel7);
        jLabel7.setBounds(460, 500, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("or");
        welcomePanel.add(jLabel8);
        jLabel8.setBounds(590, 530, 30, 40);

        lblSeller.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblSeller.setForeground(new java.awt.Color(255, 255, 255));
        lblSeller.setText("Seller");
        lblSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSellerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSellerMouseExited(evt);
            }
        });
        welcomePanel.add(lblSeller);
        lblSeller.setBounds(620, 540, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Click Here To");
        welcomePanel.add(jLabel10);
        jLabel10.setBounds(460, 460, 150, 30);

        lblLogin.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Log In");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoginMousePressed(evt);
            }
        });
        welcomePanel.add(lblLogin);
        lblLogin.setBounds(610, 460, 80, 30);

        getContentPane().add(welcomePanel);
        welcomePanel.setBounds(0, 0, 2048, 1365);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        lblLogin.setForeground(new Color(231,158,109));
        Font f= new Font("Tahoma",Font.BOLD,24);
        lblLogin.setFont(f);
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
       Font f= new Font("Tahoma",Font.ITALIC+Font.BOLD,24);
        lblLogin.setFont(f);
        lblLogin.setForeground(Color.white);
       
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseEntered
     
        Font f= new Font("Tahoma",Font.BOLD,24);
        lblCustomer.setFont(f);
        lblCustomer.setForeground(new Color(231,158,109));
    }//GEN-LAST:event_lblCustomerMouseEntered

    private void lblCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseExited
       Font f= new Font("Tahoma",Font.ITALIC+Font.BOLD,24);
       lblCustomer.setFont(f);
        lblCustomer.setForeground(Color.white);
    }//GEN-LAST:event_lblCustomerMouseExited

    private void lblSellerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellerMouseEntered
         
        Font f= new Font("Tahoma",Font.BOLD,24);
        lblSeller.setFont(f);
        lblSeller.setForeground(new Color(231,158,109));
    }//GEN-LAST:event_lblSellerMouseEntered

    private void lblSellerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellerMouseExited
       Font f= new Font("Tahoma",Font.ITALIC+Font.BOLD,24);
       lblSeller.setFont(f);
       
        lblSeller.setForeground(Color.white);
    }//GEN-LAST:event_lblSellerMouseExited

    private void lblLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMousePressed
    
    }//GEN-LAST:event_lblLoginMousePressed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        new LogIn(IP).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
        this.setVisible(false);
        new SignUpAsCustomer(IP).setVisible(true);
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblSellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellerMouseClicked
        this.setVisible(false);
        new SignUpAsSeller(IP).setVisible(true);
    }//GEN-LAST:event_lblSellerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
